# Generated by Django 6.0.2 on 2026-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('departure_time', models.TimeField(auto_now=True)),
                ('bustype', models.CharField(max_length=100)),
            ],
        ),
    ]
