# Generated by Django 6.0.2 on 2026-02-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0002_remove_busapp_totaldistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busapp',
            name='ticketprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
