# Generated by Django 6.0.2 on 2026-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0003_alter_busapp_ticketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='busapp',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
