# Generated by Django 6.0.2 on 2026-02-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0004_busapp_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='busapp',
            name='totaldistance',
            field=models.IntegerField(default=0),
        ),
    ]
