# Generated by Django 6.0.2 on 2026-02-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0005_busapp_totaldistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='busapp',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('U', 'Unidentified')], default='U', max_length=1),
        ),
    ]
