# Generated by Django 6.0.2 on 2026-02-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0006_busapp_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='busapp',
            name='dateandtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
