# Generated by Django 6.0.2 on 2026-02-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0007_busapp_dateandtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusApp',
        ),
    ]
