# Generated by Django 6.0.2 on 2026-02-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BusApp', '0008_delete_busapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('U', 'Unidentified')], default='U', max_length=1)),
                ('pickuppoint', models.CharField(max_length=100)),
                ('droppoint', models.CharField(max_length=100)),
                ('totaldistance', models.IntegerField(default=0)),
                ('dateandtime', models.DateTimeField(auto_now=True)),
                ('ticketprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
